name: actions 

on:
  schedule:
  #日本時間午後1時~3時にまわす
    - cron: '25 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 

      - name: Setup python
        uses: actions/setup-python@v2 
        with:
          python-version: "3.x" 

      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip
          pip install pandas
          pip install datetime
          pip install requests
      - name: Run jhu_update_checker.py
        run: |
          python jhu_update_checker.py
      
     # - name: Commit and Push
     #   run: |
     #     git config user.name "miotomita"
     #     git config user.email "mio.tomita@nex.nikkei.com"
     #     git add .
     #     git commit -m "daily update"
     #     git pull --rebase
     #     git push origin main
      
      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
                  {"pretext": "hello","text":"test_desu",}
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
